### ISSUE TITLE
Install?

### ISSUE THREAD

**Issue by ShardanX** [letscontrolit/GUIEasy#6]
There's not the slightest hint how to install, should be added.
Upload to ESP? Install on PC?

Unpacking of the .gz-file with 7Zip (Windows) and gzip (Linux) failed
with "Is not a .gz-File" error. Is that intended?

**Comment by Grovkillen** [comment]
It's not yet ready.

**Comment by TD-er** [comment]
Jimmy has made this repo to be able to have something "online" and some history.
So it is not only stored on his PC (and in his head ;) ), but rest assured, even I have no clue yet how to install and run it :)
